apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: eshoponweb-user003
  name: eshoponweb-deployment
  labels:
    app: eshoponweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eshoponweb
  template:
    metadata:
      labels:
        app: eshoponweb
    spec:
      containers:
      - name: eshoponweb-app
        image: aistraining.azurecr.io/eshoponwebapp-user003:1.0.0
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: aks-secret