name: Container Workflow
on: workflow_dispatch

env:
  ACR_LOGIN_SERVER: aistraining.azurecr.io
  TAG_NAME: eshoponwebapp-user003:1.0.0

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v7.0.0

      - name: ACR Login
        uses: docker/login-action@v4.4.0
        with:
            registry: ${{ env.ACR_LOGIN_SERVER }}
            username: ${{ secrets.ACR_USERNAME }}
            password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        run: |
          find . -iname "dockerfile*";
          docker build -t ${{ env.ACR_LOGIN_SERVER }}/${{ env.TAG_NAME }} .;
          docker push ${{ env.ACR_LOGIN_SERVER }}/${{ env.TAG_NAME }}