name: Container Workflow
on: workflow_dispatch

env:
  REGISTRY: aistraining.azurecr.io
  TAG_NAME: eshoponwebapp-user003:1.0.0
  AKS_RESOURCE_GROUP: rg-003
  AKS_CLUSTER_NAME: aks-demo

jobs:
  build-container:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v7.0.0

      - name: ACR Login
        uses: docker/login-action@v4.4.0
        with:
            registry: ${{ env.REGISTRY }}
            username: ${{ secrets.ACR_USERNAME }}
            password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Image
        run: |
          docker build -f src/Web/Dockerfile -t ${{ env.REGISTRY }}/${{ env.TAG_NAME }} .
          docker push ${{ env.REGISTRY }}/${{ env.TAG_NAME }}

  deploy-to-aks:
    needs: build-container
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v7.0.0

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          
      - name: Set AKS Context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ env.AKS_RESOURCE_GROUP }}
          cluster-name: ${{ env.AKS_CLUSTER_NAME }}

      - name: Set up kubectl
        uses: azure/k8s-deploy@v4.9
        with:
          manifests: |
            .k8s/deployment.yaml
            .k8s/service.yaml
          images: |
            ${{ env.REGISTRY }}/${{ env.TAG_NAME }}